apiVersion: v1
data:
  policy.csv: |
    g, anniken, role:admin
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
