apiVersion: v1
data:
  policy.csv: |
    g, anniken, role:admin
    p, *, applications, get, echoserver/echoserver, allow
    p, *, clusters, get, echoserver/echoserver, allow
    p, *, repositories, get, echoserver/echoserver, allow
    p, *, certificates, get, echoserver/echoserver, allow
    p, *, logs, get, echoserver/echoserver, allow
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
