apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bks-longhorn

resources:
- ../../base
patches:
- path: longhorn-default-settings.yaml
- target: 
    kind: Ingress
    name: longhorn-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: longhorn.p1.lab.basefarm.net 
