apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bks-longhorn

resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.7.1/deploy/longhorn.yaml
- longhorn-ingress.yaml
