apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- base/argocd-server-ingress.yaml

patches:
- path: overlays/argocd-cm.yaml
- path: overlays/argocd-cmd-params-cm.yaml
- path: overlays/argocd-server-service.yaml
- path: overlays/argocd-rbac-cm.yaml
